[project]
name = "datagenerator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "duckdb>=1.4.3",
    "faker>=40.1.0",
    "polars>=1.36.1",
    "pyarrow>=22.0.0",
]
